ci: disable ui tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,34 +94,34 @@ jobs:
         with:
           dotnet-version: 8.0.x
 
-      - name: Install Playwright Browsers and Dependencies
-        run: npx playwright install --with-deps
-
-      - name: Restore .NET dependencies
-        run: dotnet restore ./UiTests/UiTests.csproj
-
-      - name: Build UI tests
-        run: dotnet build ./UiTests/UiTests.csproj --configuration Release --nologo
-
-      - name: Run UI tests
-        run: |
-          set -o pipefail
-          dotnet test ./UiTests/UiTests.csproj \
-            --configuration Release \
-            --no-build \
-            --logger "console;verbosity=detailed" \
-            --logger "trx;LogFileName=test_results.trx" |& tee -a ci_error.txt
-        env:
-          TestSettings__BaseUrl: http://localhost:8000
-
-      - name: Upload UI test results
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: ui-test-results
-          path: /home/runner/work/krayin-laravel-crm/krayin-laravel-crm/UiTests/TestResults/test_results.trx
-          if-no-files-found: warn
-          retention-days: 14
+#      - name: Install Playwright Browsers and Dependencies
+#        run: npx playwright install --with-deps
+#
+#      - name: Restore .NET dependencies
+#        run: dotnet restore ./UiTests/UiTests.csproj
+#
+#      - name: Build UI tests
+#        run: dotnet build ./UiTests/UiTests.csproj --configuration Release --nologo
+#
+#      - name: Run UI tests
+#        run: |
+#          set -o pipefail
+#          dotnet test ./UiTests/UiTests.csproj \
+#            --configuration Release \
+#            --no-build \
+#            --logger "console;verbosity=detailed" \
+#            --logger "trx;LogFileName=test_results.trx" |& tee -a ci_error.txt
+#        env:
+#          TestSettings__BaseUrl: http://localhost:8000
+#
+#      - name: Upload UI test results
+#        if: failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ui-test-results
+#          path: /home/runner/work/krayin-laravel-crm/krayin-laravel-crm/UiTests/TestResults/test_results.trx
+#          if-no-files-found: warn
+#          retention-days: 14
 
       - name: Upload failure artifact
         if: failure()
